#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef WABOSDK_SWIFT_H
#define WABOSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WaboBase;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="WaboSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)
@class NSString;

SWIFT_CLASS("_TtC7WaboSDK18WaboAdCallbackInfo")
@interface WaboAdCallbackInfo : NSObject
@property (nonatomic) double revenue;
@property (nonatomic, copy) NSString * _Nullable network;
@property (nonatomic, copy) NSString * _Nullable placementId;
@property (nonatomic, copy) NSString * _Nullable adsourceId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK19WaboAdjustAttribute")
@interface WaboAdjustAttribute : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK19WaboAliyunLogUpload")
@interface WaboAliyunLogUpload : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK22WaboAppsflyerAttribute")
@interface WaboAppsflyerAttribute : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WaboAttrInfoBuilder;

SWIFT_CLASS("_TtC7WaboSDK12WaboAttrInfo")
@interface WaboAttrInfo : NSObject
@property (nonatomic, copy) NSString * _Nonnull trackerToken;
@property (nonatomic, copy) NSString * _Nonnull trackerName;
@property (nonatomic, copy) NSString * _Nullable attrid;
@property (nonatomic, copy) NSString * _Nullable network;
@property (nonatomic, copy) NSString * _Nullable campaign;
@property (nonatomic, copy) NSString * _Nullable adgroup;
@property (nonatomic, copy) NSString * _Nullable creative;
@property (nonatomic, copy) NSString * _Nullable fbInstallReferrer;
+ (WaboAttrInfoBuilder * _Nonnull)Builder SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK19WaboAttrInfoBuilder")
@interface WaboAttrInfoBuilder : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7WaboSDK19WaboAutoLoginResult")
@interface WaboAutoLoginResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic) BOOL isNew;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK26WaboBindTransferCodeResult")
@interface WaboBindTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK21WaboBuglyCrashMonitor")
@interface WaboBuglyCrashMonitor : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK20WaboCheckLoginResult")
@interface WaboCheckLoginResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK16WaboCollectLogin")
@interface WaboCollectLogin : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK16WaboCollectShare")
@interface WaboCollectShare : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK11WaboFactory")
@interface WaboFactory : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC7WaboSDK20WaboFirebaseAnalysis")
@interface WaboFirebaseAnalysis : NSObject <WaboThirdUploadLoggerProtocol>
- (void)registerEvent;
- (void)login;
- (void)level:(NSInteger)level;
- (void)subscription:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)orderId;
- (void)adShow:(NSString * _Nonnull)adType :(NSString * _Nonnull)mediationPlatform :(NSString * _Nonnull)networkName :(NSString * _Nonnull)displayName :(NSString * _Nonnull)adUnitId :(double)revenue;
- (void)addToCart:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId;
- (void)initCheckout:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId SWIFT_METHOD_FAMILY(none);
- (void)purchase:(double)price :(NSString * _Nonnull)currency :(NSString * _Nonnull)contentId :(NSString * _Nonnull)transacationId;
- (void)incRevenue:(double)price;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK30WaboGenerateTransferCodeResult")
@interface WaboGenerateTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable transferCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK29WaboGetBindTransferCodeResult")
@interface WaboGetBindTransferCodeResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK13WaboGoogleUMP")
@interface WaboGoogleUMP : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK15WaboIapPurchase")
@interface WaboIapPurchase : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK13WaboLoginInfo")
@interface WaboLoginInfo : NSObject
@property (nonatomic, copy) NSString * _Nullable platform;
@property (nonatomic) BOOL hasLinked;
@property (nonatomic, copy) NSString * _Nullable uniqeId;
@property (nonatomic, copy) NSString * _Nullable iconUrl;
@property (nonatomic, copy) NSString * _Nullable nickName;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK15WaboLoginParams")
@interface WaboLoginParams : NSObject
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic, copy) NSDictionary<NSString *, NSString *> * _Nonnull params;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK15WaboLoginResult")
@interface WaboLoginResult : NSObject
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSString * _Nullable loginType;
@property (nonatomic, copy) NSString * _Nullable sessionToken;
@property (nonatomic) BOOL isNew;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK18WaboMaxAdvertising")
@interface WaboMaxAdvertising : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK15WaboOneTimeItem")
@interface WaboOneTimeItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic) int64_t purchaseTime;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK17WaboPaymentResult")
@interface WaboPaymentResult : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) int64_t gameOrderId;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) NSInteger status;
@property (nonatomic) NSInteger type;
@property (nonatomic, readonly) BOOL isConsume;
@property (nonatomic, readonly) BOOL isOneTime;
@property (nonatomic, readonly) BOOL isSubscription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol WaboSDKDelegate;

SWIFT_CLASS("_TtC7WaboSDK7WaboSDK")
@interface WaboSDK : NSObject
+ (WaboSDK * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (BOOL)hasInit SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)getStaticInfoOfString SWIFT_WARN_UNUSED_RESULT;
- (void)sdkInit:(id <WaboSDKDelegate> _Nonnull)delegate;
- (void)sdkInitWithDict:(NSDictionary<NSString *, id> * _Nonnull)configDict delegate:(id <WaboSDKDelegate> _Nonnull)delegate;
- (void)sdkInitWithJson:(NSString * _Nonnull)configJson delegate:(id <WaboSDKDelegate> _Nonnull)delegate;
- (void)onWaboUMPInitDelegate:(id _Nullable)any;
- (void)onWaboCrashMonitorInitDelegate:(id _Nullable)any;
- (void)onWaboAttributeInitDelegate:(id _Nullable)any;
- (void)onWaboAttributeChangedDelegate:(id _Nullable)any;
- (void)onWaboAdvertisingInitDelegate:(id _Nullable)any;
- (void)onWaboAdvertisingAppopenAdDelegate:(id _Nullable)any;
- (void)onWaboAdvertisingRewardedAdDelegate:(id _Nullable)any;
- (void)onWaboAdvertisingInterstitialAdDelegate:(id _Nullable)any;
- (void)onWaboAdvertisingBannerAdDelegate:(id _Nullable)any;
- (void)onWaboLogUploadInitDelegate:(id _Nullable)any;
- (void)onWaboAnalysisInitDelegate:(id _Nullable)any;
- (void)onWaboLoginInitDelegate:(id _Nullable)any;
- (void)onWaboPurchaseInitDelegate:(id _Nullable)any;
- (void)onWaboShareInitDelegate:(id _Nullable)any;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
/// get attr info
///
/// returns:
/// attr info
- (WaboAttrInfo * _Nullable)getAttrInfo SWIFT_WARN_UNUSED_RESULT;
/// get attribution id
///
/// returns:
/// attribution id
- (NSString * _Nullable)getAttrId SWIFT_WARN_UNUSED_RESULT;
@end


@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (NSInteger)tryLaunchOrOpenAppStore:(NSString * _Nonnull)appURLScheme :(NSString * _Nonnull)appStoreURL :(NSDictionary<NSString *, id> * _Nullable)dataDict SWIFT_WARN_UNUSED_RESULT;
- (void)setAppJumpDelegate:(void (^ _Nonnull)(NSDictionary<NSString *, id> * _Nonnull))delegate;
@end


@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (void)onMessaging:(NSString * _Nonnull)token;
- (void)enableRemoteNotifications;
- (void)disableRemoteNotifications;
@end

@class WaboStatusCode;
@class UIImage;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (NSArray<NSString *> * _Nonnull)getShareTypes SWIFT_WARN_UNUSED_RESULT;
- (void)shareLink:(NSString * _Nonnull)shareType url:(NSString * _Nonnull)url success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)sharePhoto:(NSString * _Nonnull)shareType image:(UIImage * _Nonnull)image success:(void (^ _Nonnull)(NSString * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
@end

@class UIApplication;
@class NSURL;
@class UIScene;
@class UISceneSession;
@class UISceneConnectionOptions;
@class UIOpenURLContext;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url options:(NSDictionary<UIApplicationOpenURLOptionsKey, id> * _Nonnull)options SWIFT_WARN_UNUSED_RESULT;
- (BOOL)application:(UIApplication * _Nonnull)application openURL:(NSURL * _Nonnull)url sourceApplication:(NSString * _Nullable)sourceApplication annotation:(id _Nonnull)annotation SWIFT_WARN_UNUSED_RESULT;
- (void)scene:(UIScene * _Nonnull)scene willConnectTo:(UISceneSession * _Nonnull)session options:(UISceneConnectionOptions * _Nonnull)connectionOptions SWIFT_AVAILABILITY(ios,introduced=13.0);
- (void)scene:(UIScene * _Nonnull)scene openURLContexts:(NSSet<UIOpenURLContext *> * _Nonnull)URLContexts SWIFT_AVAILABILITY(ios,introduced=13.0);
@end

@class NSDate;
@class WaboCustomEvent;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (void)onLog:(NSString * _Nonnull)eventName paramMap:(NSDictionary<NSString *, id> * _Nonnull)paramMap;
- (void)onLogPaySuccess:(NSString * _Nonnull)store transactionId:(NSString * _Nonnull)transactionId productId:(NSString * _Nonnull)productId purchaseDate:(NSDate * _Nonnull)purchaseDate price:(double)price priceString:(NSString * _Nonnull)priceString currency:(NSString * _Nonnull)currency;
- (void)onUploadIntoGame:(NSString * _Nullable)server_id server_name:(NSString * _Nullable)server_name role_id:(NSString * _Nullable)role_id role_name:(NSString * _Nullable)role_name;
- (void)onLogWithJson:(NSString * _Nonnull)jsonString;
- (void)onUploadCustomEvent:(WaboCustomEvent * _Nonnull)customEvent;
@end

enum WaboUMPDebugGeography : NSInteger;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (NSString * _Nonnull)getUMPParameters SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isPrivacyOptionsRequired SWIFT_WARN_UNUSED_RESULT;
- (void)showPrivacyOptionsForm:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))block;
- (void)setDebugGeography:(enum WaboUMPDebugGeography)debugGeography;
- (void)addTestDeviceHashedId:(NSString * _Nonnull)deviceHashedId;
@end


@class WaboUserInfoResult;
@class WaboSignOutResult;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
@property (nonatomic, readonly, copy) NSString * _Nullable gameId;
@property (nonatomic, readonly) BOOL isLogin;
@property (nonatomic, readonly) int64_t gameAccountId;
@property (nonatomic, readonly, copy) NSString * _Nullable sessionToken;
- (NSArray<NSString *> * _Nonnull)getLoginTypes SWIFT_WARN_UNUSED_RESULT;
- (void)uploadRoleLogin:(NSString * _Nonnull)serverId serverName:(NSString * _Nonnull)serverName roleId:(NSString * _Nonnull)roleId roleName:(NSString * _Nonnull)roleName;
- (void)autoLoginAsync:(BOOL)needGameCenter success:(void (^ _Nonnull)(WaboAutoLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)checkLoginAsync:(void (^ _Nonnull)(WaboCheckLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)loginWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(WaboLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)bindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(WaboUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)unbindWithTypeAsync:(NSString * _Nonnull)loginType success:(void (^ _Nonnull)(WaboUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)getUserInfoAsync:(void (^ _Nonnull)(WaboUserInfoResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)logout;
- (void)signOut:(void (^ _Nonnull)(WaboSignOutResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)getBindTransferCode:(void (^ _Nonnull)(WaboGetBindTransferCodeResult * _Nullable))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)generateTransferCode:(void (^ _Nonnull)(WaboGenerateTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)bindTransferCode:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(WaboBindTransferCodeResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)bindTransferCodeAndReLogin:(NSString * _Nonnull)transferCode success:(void (^ _Nonnull)(WaboLoginResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
@end

@class UIView;
@class UIColor;
@protocol WaboSDKNativeAdDelegate;
@class WaboNativeAdBinder;
@protocol WaboSDKAppopenAdDelegate;
@protocol WaboSDKRewardAdDelegate;
@protocol WaboSDKInterstitialAdDelegate;
@protocol WaboSDKBannerAdDelegate;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (NSString * _Nonnull)getLoadingStatusSummary SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isRewardedAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showRewardedAd:(NSString * _Nullable)placementId;
- (BOOL)isInterstitialAdReady:(NSString * _Nullable)placementId SWIFT_WARN_UNUSED_RESULT;
- (void)showInterstitialAd:(NSString * _Nullable)placementId;
- (void)setBannerCustomMode:(BOOL)bannerCustomMode;
- (UIView * _Nullable)createBanner SWIFT_WARN_UNUSED_RESULT;
- (void)destroyBanner;
- (CGSize)getBannerSize SWIFT_WARN_UNUSED_RESULT;
- (void)setBannerBackgroundColor:(UIColor * _Nonnull)color;
- (BOOL)isBannerAdReady SWIFT_WARN_UNUSED_RESULT;
- (void)showBannerAd;
- (void)hideBannerAd;
- (void)showBannerAdTop;
- (void)showBannerAdBottom;
- (void)showBannerAdTopOfSafe;
- (void)showBannerAdBottomOfSafe;
- (void)showBannerAdWithPosition:(float)x :(float)y;
- (void)showAppopenAdWithTimeout:(float)timeout;
- (void)showSmallNativeAd:(id <WaboSDKNativeAdDelegate> _Nullable)delegate;
- (void)showMediumNativeAd:(id <WaboSDKNativeAdDelegate> _Nullable)delegate;
- (void)showManualNativeAdWithBinder:(WaboNativeAdBinder * _Nonnull)binder delegate:(id <WaboSDKNativeAdDelegate> _Nullable)delegate;
- (void)destroyNativeAdView:(UIView * _Nonnull)view;
- (void)setWaboAppopenAdDelegate:(id <WaboSDKAppopenAdDelegate> _Nonnull)delegate;
- (void)setWaboRewardAdDelegate:(id <WaboSDKRewardAdDelegate> _Nonnull)delegate;
- (void)setWaboInterstitialAdDelegate:(id <WaboSDKInterstitialAdDelegate> _Nonnull)delegate;
- (void)setWaboBannerAdDelegate:(id <WaboSDKBannerAdDelegate> _Nonnull)delegate;
@end

@protocol WaboSDKWebAdDelegate;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (void)setWaboWebAdDelegate:(id <WaboSDKWebAdDelegate> _Nonnull)delegate;
- (BOOL)isWebAdReady SWIFT_WARN_UNUSED_RESULT;
- (void)showUrl;
@end

@class WaboShopItem;
@class WaboSubscriptionItem;

@interface WaboSDK (SWIFT_EXTENSION(WaboSDK))
- (void)setWaboTransactionStatusDelegate:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))delegate;
- (NSArray<WaboShopItem *> * _Nullable)getShopItems SWIFT_WARN_UNUSED_RESULT;
- (void)getShopItemsAsyncWithSuccecc:(void (^ _Nonnull)(NSArray<WaboShopItem *> * _Nonnull))succecc failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)startPayment:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId success:(void (^ _Nonnull)(WaboPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)startPaymentWithEnvId:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId envId:(NSString * _Nonnull)envId success:(void (^ _Nonnull)(WaboPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)startPaymentWithExtraInfo:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId extraInfo:(NSDictionary<NSString *, NSString *> * _Nonnull)extraInfo success:(void (^ _Nonnull)(WaboPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)startPaymentWithEnvIdAndExtraInfo:(NSString * _Nonnull)itemId cpOrderId:(NSString * _Nullable)cpOrderId envId:(NSString * _Nullable)envId extraInfo:(NSDictionary<NSString *, NSString *> * _Nullable)extraInfo success:(void (^ _Nonnull)(WaboPaymentResult * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)onConsumeItem:(int64_t)gameOrderId success:(void (^ _Nonnull)(int64_t))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)queryOneTimeItemAsync:(void (^ _Nonnull)(NSArray<WaboOneTimeItem *> * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)querySubscriptionAsync:(void (^ _Nonnull)(NSArray<WaboSubscriptionItem *> * _Nonnull))success failed:(void (^ _Nonnull)(WaboStatusCode * _Nonnull))failed;
- (void)onRestoreApplePurchases;
- (void)onRestoreApplePurchasesWithCallback:(void (^ _Nonnull)(NSString * _Nonnull))callback;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK24WaboSDKAppopenAdDelegate_")
@protocol WaboSDKAppopenAdDelegate <NSObject>
- (void)onWaboAppopenAdDidLoad:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboAppopenAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onWaboAppopenAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboAppopenAdDidHide:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboAppopenAdDidClick:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboAppopenAdDidFailToDisplay:(NSString * _Nonnull)adUnitId code:(NSInteger)code errMsg:(NSString * _Nonnull)errMsg;
- (void)onWaboAppopenAdDiaTimeout:(NSString * _Nonnull)adUnitId;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK23WaboSDKBannerAdDelegate_")
@protocol WaboSDKBannerAdDelegate <NSObject>
- (void)onWaboBannerAdDidLoad:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboBannerAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onWaboBannerAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboBannerAdDidHide:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboBannerAdDidExpand:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboBannerAdDidClick:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_CLASS("_TtC7WaboSDK13WaboSDKConfig")
@interface WaboSDKConfig : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class WaboUnConsumeItem;

SWIFT_PROTOCOL("_TtP7WaboSDK15WaboSDKDelegate_")
@protocol WaboSDKDelegate <NSObject>
- (void)onWaboSdkInitResult:(WaboStatusCode * _Nonnull)statusCode;
@optional
- (void)onWaboSdkAttrChanged:(WaboAttrInfo * _Nullable)attrInfo;
- (void)onWaboSdkAdvertisingActive;
- (void)onWaboSdkPullUnConsumeItems:(NSArray<WaboUnConsumeItem *> * _Nonnull)unConsmeItems;
- (void)onWaboSdkPullOneTimeItems:(NSArray<WaboOneTimeItem *> * _Nonnull)oneTimeItems;
- (void)onWaboSdkPullSubscriptionItems:(NSArray<WaboSubscriptionItem *> * _Nonnull)subscriptionItems;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK29WaboSDKInterstitialAdDelegate_")
@protocol WaboSDKInterstitialAdDelegate <NSObject>
- (void)onWaboInterstitialAdDidLoad:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboInterstitialAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onWaboInterstitialAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboInterstitialAdDidHide:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboInterstitialAdDidClick:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK23WaboSDKNativeAdDelegate_")
@protocol WaboSDKNativeAdDelegate <NSObject>
- (void)onWaboNativeAdDidLoad:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo view:(UIView * _Nullable)view;
- (void)onWaboNativeAdDidFailToLoad:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onWaboNativeAdDidClick:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboNativeAdDidRevenue:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK23WaboSDKRewardAdDelegate_")
@protocol WaboSDKRewardAdDelegate <NSObject>
- (void)onWaboRewardAdDidRewardUser:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboRewardAdDidLoad:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboRewardAdDidFailToLoadAd:(NSString * _Nonnull)adUnitId errorCode:(NSInteger)errorCode errorMsg:(NSString * _Nonnull)errorMsg;
- (void)onWaboRewardAdDidDisplay:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboRewardAdDidHide:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboRewardAdDidClick:(NSString * _Nonnull)adUnitId callback:(WaboAdCallbackInfo * _Nonnull)callbackInfo;
- (void)onWaboRewardAdDidFailToDisplay:(NSString * _Nonnull)adUnitId code:(NSInteger)code errMsg:(NSString * _Nonnull)errMsg;
@end


SWIFT_PROTOCOL("_TtP7WaboSDK20WaboSDKWebAdDelegate_")
@protocol WaboSDKWebAdDelegate <NSObject>
@optional
- (void)onWaboWebAdLoaded;
- (void)onWaboWebAdLoadFailed:(NSString * _Nonnull)errorMsg;
- (void)onWaboWebAdClose;
- (void)onWaboWebAdPlayStart;
- (void)onWaboWebAdPlayFailed:(NSString * _Nonnull)errorMsg;
- (void)onWaboWebAdReward:(NSString * _Nonnull)msg;
@end


SWIFT_CLASS("_TtC7WaboSDK12WaboShopItem")
@interface WaboShopItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) NSInteger type;
@property (nonatomic, copy) NSString * _Nullable appleStoreId;
@property (nonatomic, copy) NSString * _Nullable usdPrice;
@property (nonatomic, copy) NSString * _Nullable formattedPrice;
@property (nonatomic, readonly, copy) NSString * _Nullable itemType;
@property (nonatomic, copy) NSString * _Nullable currency;
@property (nonatomic, readonly, copy) NSString * _Nullable price;
@property (nonatomic, readonly) BOOL isConsume;
@property (nonatomic, readonly) BOOL isOneTime;
@property (nonatomic, readonly) BOOL isSubscription;
@end


SWIFT_CLASS("_TtC7WaboSDK17WaboSignOutResult")
@interface WaboSignOutResult : NSObject
@property (nonatomic) NSInteger code;
@property (nonatomic, copy) NSString * _Nullable msg;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK20WaboSubscriptionItem")
@interface WaboSubscriptionItem : NSObject
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic, copy) NSString * _Nullable productId;
@property (nonatomic, copy) NSString * _Nullable originalTransactionId;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) int64_t expiredTime;
@property (nonatomic) int64_t leftTime;
@property (nonatomic) BOOL isSubscribed;
@property (nonatomic) BOOL isInFree;
@property (nonatomic) BOOL isInIntroductory;
@property (nonatomic) BOOL isCancel;
@end

typedef SWIFT_ENUM(NSInteger, WaboUMPDebugGeography, closed) {
  WaboUMPDebugGeographyDisabled = 0,
  WaboUMPDebugGeographyEEA = 1,
  WaboUMPDebugGeographyNotEEA = 2,
};


SWIFT_CLASS("_TtC7WaboSDK17WaboUnConsumeItem")
@interface WaboUnConsumeItem : NSObject
@property (nonatomic) int64_t gameOrderId;
@property (nonatomic, copy) NSString * _Nullable itemId;
@property (nonatomic) int64_t createTime;
@property (nonatomic) int64_t purchaseTime;
@property (nonatomic) NSInteger status;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC7WaboSDK18WaboUserInfoResult")
@interface WaboUserInfoResult : NSObject
@property (nonatomic, copy) NSString * _Nullable gameId;
@property (nonatomic) int64_t gameAccountId;
@property (nonatomic, copy) NSString * _Nullable saveGameId;
@property (nonatomic) int64_t saveId;
@property (nonatomic, copy) NSArray<WaboLoginInfo *> * _Nullable loginInfo;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
